'use strict';
// 从HTML的实际Three.js网格检查运动学、销轴局部配合与全行程非配合包络。
// node verify_near_joint.cjs [--step=0.05] [--no-write]
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const THREE=require('./.verification/three-r128.cjs');
const root=__dirname,html=fs.readFileSync(path.join(root,'arm_mechanism_3d.html'),'utf8');
const script=[...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)].find(m=>m[1].includes('const P ='))[1];
new Function(script);
const nodes=new Map(),document={getElementById(id){if(!nodes.has(id))nodes.set(id,{});return nodes.get(id);}};
const main=script.slice(0,script.lastIndexOf('\ninitScene();'));
const api=new Function('THREE','document',main+'\nscene=new THREE.Scene();showLabels=false;buildMechanism();updateMechanism(0);return {P,s,scene,updateMechanism,getDPoint,angleToStroke,getStrokeFromAngle,strokeToAngle,getForceData,transmissionAngle};')(THREE,document);
const {P,s,scene}=api;
function classify(mesh){const n=[];for(let p=mesh;p;p=p.parent)n.push(p.name);if(n.includes('upperArm'))return'upperArm';if(n.includes('forearm'))return'forearm';if(n.includes('tendonGroup'))return'tendon';if(n.includes('motor'))return n.includes('motorRod')?'motorSlider':'motorFixed';return'other';}
const meshes=[];
scene.traverse(o=>{if(!o.isMesh)return;for(let p=o;p;p=p.parent)if(p.name==='bodyOutline')return;assert(o.name,'Physical mesh needs a unique name');meshes.push({mesh:o,assembly:classify(o)});});
assert.equal(new Set(meshes.map(x=>x.mesh.name)).size,meshes.length);
assert(!meshes.some(x=>/guide|Offset|sideEar/.test(x.mesh.name)));
const cross=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);
function hull(points){const p=[...new Map(points.map(v=>[v.map(x=>x.toFixed(9)).join(','),v])).values()].sort((a,b)=>a[0]-b[0]||a[1]-b[1]);if(p.length<3)return p;const lo=[],hi=[];for(const v of p){while(lo.length>1&&cross(lo.at(-2),lo.at(-1),v)<=1e-10)lo.pop();lo.push(v);}for(const v of p.slice().reverse()){while(hi.length>1&&cross(hi.at(-2),hi.at(-1),v)<=1e-10)hi.pop();hi.push(v);}return lo.slice(0,-1).concat(hi.slice(0,-1));}
function clip(a,b){let out=a;for(let j=0;j<b.length&&out.length;j++){const q=b[j],r=b[(j+1)%b.length],input=out;out=[];for(let i=0;i<input.length;i++){const u=input[i],v=input[(i+1)%input.length],cu=cross(q,r,u),cv=cross(q,r,v),iu=cu>=-1e-8,iv=cv>=-1e-8;if(iu)out.push(u);if(iu!==iv){const t=cu/(cu-cv);out.push([u[0]+t*(v[0]-u[0]),u[1]+t*(v[1]-u[1])]);}}}return out;}
const area=p=>Math.abs(p.reduce((a,v,i)=>{const w=p[(i+1)%p.length];return a+v[0]*w[1]-v[1]*w[0];},0))/2;
function pointSeg(p,a,b){const dx=b[0]-a[0],dy=b[1]-a[1],d=dx*dx+dy*dy,t=d?Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dy)/d)):0;return Math.hypot(p[0]-a[0]-t*dx,p[1]-a[1]-t*dy);}
function distance(a,b){let d=Infinity;for(const [p,q] of [[a,b],[b,a]])for(const v of p)for(let i=0;i<q.length;i++)d=Math.min(d,pointSeg(v,q[i],q[(i+1)%q.length]));return d;}
const prepared=meshes.map(({mesh,assembly})=>{const a=mesh.geometry.attributes.position,local=[...new Map(Array.from({length:a.count},(_,i)=>[a.getX(i),a.getY(i),a.getZ(i)]).map(p=>[p.join(','),p])).values()];return{mesh,assembly,local};});
function projection({mesh,assembly,local}){const e=mesh.matrixWorld.elements,g=mesh.geometry,cx=e[12]/s,cy=e[13]/s;let xy,zmin=Infinity,zmax=-Infinity;if(g.type==='SphereGeometry'||(g.type==='CylinderGeometry'&&Math.abs(e[6])>0.9)){const r=(g.parameters.radius||g.parameters.radiusTop)/s/Math.cos(Math.PI/32);xy=Array.from({length:32},(_,i)=>[cx+r*Math.cos(2*Math.PI*i/32),cy+r*Math.sin(2*Math.PI*i/32)]);}else xy=hull(local.map(p=>[(e[0]*p[0]+e[4]*p[1]+e[8]*p[2]+e[12])/s,(e[1]*p[0]+e[5]*p[1]+e[9]*p[2]+e[13])/s]));for(const p of local){const z=(e[2]*p[0]+e[6]*p[1]+e[10]*p[2]+e[14])/s;zmin=Math.min(zmin,z);zmax=Math.max(zmax,z);}return{name:mesh.name,assembly,xy,zmin,zmax};}
const key=(a,b)=>[a,b].sort().join(' / ');
function skip(a,b){if(a.assembly===b.assembly)return'同一刚性子总成';const set=new Set([a.assembly,b.assembly]);if(set.has('upperArm')&&set.has('motorFixed')){const n=a.assembly==='motorFixed'?a.name:b.name;if(/^(upperClamp|lowerClamp)/.test(n))return'抱箍与上臂固定连接';}if([key('exposedRod','motorFrontCap'),key('exposedRod','motorBody')].includes(key(a.name,b.name)))return'电机同轴导向与推杆滑动配合';return null;}
function zone(a,b){const set=new Set([a.assembly,b.assembly]);if(set.has('upperArm')&&set.has('forearm'))return{name:'O',r:18};if(set.has('forearm')&&set.has('tendon'))return{name:'D',r:9};if(set.has('motorSlider')&&set.has('tendon'))return{name:'B',r:9};return null;}
const arg=process.argv.find(a=>a.startsWith('--step=')),step=arg?Number(arg.split('=')[1]):0.05;assert(step>0&&step<=0.5);
const samples=Math.round(120/step)+1,pairStats=new Map(),collisions=[],table=[];let closure=0,inverse=0,jerr=0,minJ=Infinity,minMu=Infinity,peakF=0,minRod=Infinity,maxRod=0;
for(let i=0;i<samples;i++){
 const deg=120*i/(samples-1);api.updateMechanism(deg);scene.updateMatrixWorld(true);
 const D=api.getDPoint(deg),By=P.motorMountY-api.angleToStroke(deg),B={x:P.motorMountX,y:By},joints={O:[0,0],B:[B.x,B.y],D:[D.x,D.y]},shapes=prepared.map(projection),f=api.getForceData(deg),u=api.getStrokeFromAngle(deg);
 closure=Math.max(closure,Math.abs(Math.hypot(B.x-D.x,B.y-D.y)-P.tendonLinkLen));inverse=Math.max(inverse,Math.abs(api.strokeToAngle(u)-deg));const ep=1e-4,fd=(api.getStrokeFromAngle(deg+ep)-api.getStrokeFromAngle(deg-ep))/(2*ep*Math.PI/180);jerr=Math.max(jerr,Math.abs(fd-f.J));minJ=Math.min(minJ,f.J);minMu=Math.min(minMu,api.transmissionAngle(deg));peakF=Math.max(peakF,f.forceN);const rod=P.motorMountY-P.motorBodyLen-By;minRod=Math.min(minRod,rod);maxRod=Math.max(maxRod,rod);
 if(Math.abs(deg/15-Math.round(deg/15))<1e-8)table.push({angle_deg:deg,retraction_mm:u,AB_distance_mm:P.motorMountY-By,exposed_rod_mm:rod,B:{...B,z:0},D:{...D,z:0},J_mm_per_rad:f.J,acute_transmission_angle_deg:api.transmissionAngle(deg),ideal_5kg_force_N:f.forceN});
 for(let a=0;a<shapes.length;a++)for(let b=a+1;b<shapes.length;b++){const A=shapes[a],C=shapes[b];if(skip(A,C))continue;const k=key(A.name,C.name),z=zone(A,C);let st=pairStats.get(k);if(!st){st={pair:k,assemblies:[A.assembly,C.assembly],min_clearance_mm:Infinity,angle_deg:null,mating_zone:z,max_contact_radius_mm:0};pairStats.set(k,st);}const inter=clip(A.xy,C.xy),contact=inter.length>0&&area(inter)>1e-8,zover=Math.min(A.zmax,C.zmax)-Math.max(A.zmin,C.zmin);if(contact&&zover>1e-7){const r=z?Math.max(...inter.map(p=>Math.hypot(p[0]-joints[z.name][0],p[1]-joints[z.name][1]))):Infinity;if(z&&r<=z.r)st.max_contact_radius_mm=Math.max(st.max_contact_radius_mm,r);else if(collisions.length<100)collisions.push({angle_deg:deg,pair:k,assemblies:[A.assembly,C.assembly],projected_overlap_mm2:area(inter),outside_mating_radius_mm:z?r-z.r:null});}if(!z){const gz=Math.max(0,A.zmin-C.zmax,C.zmin-A.zmax),d=contact?gz:Math.hypot(distance(A.xy,C.xy),gz);if(d<st.min_clearance_mm){st.min_clearance_mm=d;st.angle_deg=deg;}}}
}
const rD=Math.hypot(P.forearmAttachDist,P.forearmAttachOffset),dx=Math.abs(P.motorMountX)+rD,h=Math.sqrt(P.tendonLinkLen**2-dx**2);assert(Number.isFinite(h)&&h>0);const Jb=rD+dx*rD/h,phib=rD/h,vb=(rD+Jb)/2+Math.hypot(P.tendonLinkLen/2,P.linkEyeRadius)*phib;assert(Math.max(P.forearmLen+20,rD+25,Jb,vb)<400);
const allowance=400*(120/(samples-1))*Math.PI/180,regular=[...pairStats.values()].filter(p=>!p.mating_zone).sort((a,b)=>a.min_clearance_mm-b.min_clearance_mm),local=[...pairStats.values()].filter(p=>p.mating_zone);
const report={version:'classic-clevis-cylinder-v2',status:'名义刚性几何与销轴配合包络核验；非制造/强度认证',parameters:P,source:'arm_mechanism_3d.html',changes:{motor:`Ø${2*P.motorBodyRadius}x${P.motorBodyLen}mm圆柱体；轴线x=${P.motorMountX}mm；上/下双抱箍`,motor_mount_mm:[P.motorMountX,P.motorMountY,0],link:`${P.tendonLinkLen}mm狗骨形中置连杆，B/D双剪叉耳`,D_local_mm:[P.forearmAttachOffset,-P.forearmAttachDist,0],joints:`O Ø${2*P.elbowPinRadius}mm双支撑；B/D Ø${2*P.linkPinRadius}mm销轴、衬套、销头和锁紧螺母`,actuation_plane_z_mm:0},load_assumption:{payload_kg:5,payload_distance_mm:250,g:9.81,excluded:['arm/link self-weight','friction','inertia','impact','efficiency losses']},input_definition:`u=By(theta)-By(0), retraction flexes arm; AB=${P.motorMountY}-By, exposed rod=${P.motorMountY-P.motorBodyLen}-By; all lengths mm, all rotation derivatives per radian.`,velocity_bound:{D_radius_mm:rD,h_min_bound_mm:h,J_absolute_bound_mm_per_rad:Jb,link_angular_speed_bound:phib,link_vertex_speed_bound_mm_per_rad:vb,selected_common_bound_mm_per_rad:400},results:{A_to_O_mm:Math.hypot(P.motorMountX,P.motorMountY),motor_to_upper_arm_nominal_gap_mm:P.motorMountX-P.motorBodyRadius-8,stroke_mm:P.strokeMax,min_J_mm_per_rad:minJ,min_acute_mu_deg:minMu,ideal_5kg_static_peak_force_N:peakF,exposed_rod_min_mm:minRod,exposed_rod_max_mm:maxRod},verification:{samples,step_deg:120/(samples-1),physical_mesh_count:meshes.length,names:meshes.map(x=>({name:x.mesh.name,assembly:x.assembly})),tested_pairs:pairStats.size,closure_error_mm:closure,inverse_error_deg:inverse,jacobian_error:jerr,collision_count_recorded:collisions.length,collisions,circle_projection:'沿Z销轴、轴套与耳环使用32边外切多边形保守覆盖；其余取实际网格凸投影和Z范围',min_non_mating_clearance_mm:regular[0]?.min_clearance_mm,minimum_pair:regular[0]?.pair,inter_sample_distance_allowance_mm:allowance,continuous_non_mating_lower_bound_mm:regular[0]?.min_clearance_mm-allowance,non_mating_pairs:regular,local_mating_contact_checks:local,fixed_fit_exclusions:['每个刚性子总成内部零件固定接触','上下抱箍与上臂固定接触','电机缸体/前盖导向与外露推杆滑动配合'],reference_exclusions:['标签与轨迹','网格地面/阴影','半透明人体参考'],limitation:'局部销孔用重叠轴套/销轴图元表达；未建真实孔隙、螺纹、止推游隙和载荷变形。全配对名义包络核验不等于制造或承载认证。'},table};
console.log(JSON.stringify({results:report.results,verification:{samples,physical_meshes:meshes.length,tested_pairs:pairStats.size,collisions:collisions.slice(0,20),closest:regular.slice(0,12),local_contacts:local.length,continuous_lower_bound_mm:report.verification.continuous_non_mating_lower_bound_mm}},null,2));
assert(closure<1e-8&&inverse<1e-7&&jerr<1e-6&&minJ>0&&minRod>0);assert(P.strokeMax>=50&&P.strokeMax<=60);assert(report.results.motor_to_upper_arm_nominal_gap_mm>=1);assert.equal(collisions.length,0,'Detected contact outside declared joint/assembly fits');assert(report.verification.continuous_non_mating_lower_bound_mm>0,'No intersample clearance guarantee');
if(!process.argv.includes('--no-write'))fs.writeFileSync(path.join(root,'arm_near_joint_params.json'),JSON.stringify(report,null,2)+'\n');
module.exports={api,report};
